// app/(your_path)/_data/recommendation-data.js

const recommendationPrompts = [
  "Something creative to use up leftover rice and veggies",
  "A spicy green curry with tofu and lemongrass, low sodium",
  "An Italian-inspired salad with parmesan cheese and chickpeas",
  "A hearty vegan stew with lentils and root vegetables",
  "A 15-minute healthy breakfast using oats and berries",
  "A comfort dinner using only pantry staples",
  "A one-pot dish with chicken, tomatoes, and herbs",
  "A gluten-free dessert idea with chocolate and bananas",
  "A light summer pasta with zucchini and lemon",
  "A budget-friendly high-protein lunch with eggs and beans",
  "A Thai-inspired noodle salad with peanut dressing",
  "A fusion twist using kimchi and cheese",
  "An energy-boosting smoothie with greens and seeds",
  "An easy lunchbox meal for kids under 20 minutes",
  "A Mediterranean bowl with hummus, falafel, and couscous",
  "A plant-based BBQ idea using mushrooms",
  "A meal-prep friendly curry that lasts all week",
  "A quick stir-fry with soy sauce and seasonal veggies",
  "A festive dish for holidays that’s simple to make",
  "A slow-cooker meal using beef and root vegetables",
  "A protein-packed breakfast wrap with avocado and eggs",
  "A low-carb dinner with cauliflower rice and grilled fish",
  "An air fryer snack using sweet potatoes and spices",
  "A no-bake dessert with coconut and dark chocolate",
  "A rainy day comfort soup with noodles and veggies",
  "A microwave-friendly mug cake using pantry ingredients",
  "A dairy-free creamy pasta using cashew sauce",
  "A picnic-friendly wrap with hummus and roasted veggies",
  "A quick dinner with canned beans and tortillas",
  "A fancy date night dish with steak and red wine sauce",
  "A cozy autumn soup with pumpkin and sage",
  "A post-workout smoothie with protein and berries",
  "A Japanese-style rice bowl with tamari and tofu",
  "A refreshing ceviche with citrus and herbs",
  "A cozy hot chocolate twist with spices and oat milk",
  "An Indian-inspired dal with turmeric and cumin",
  "A bento box idea with rice, edamame, and pickled veg",
  "A low-waste meal using all your veggie scraps",
  "A spicy ramen with miso and crunchy toppings",
  "A savory breakfast bowl with greens and poached eggs",
  "A Caribbean-inspired jerk chicken with pineapple salsa",
  "A quick taco night idea with beans and avocado",
  "A fancy brunch toast with smoked salmon and dill",
];

export default recommendationPrompts;
