import { PrismaClient } from "@/lib/generated/prisma"

const prisma = new PrismaClient()

const sampleRecipes = [
  // Italian Recipes
  {
    title: "Classic Margherita Pizza",
    description: "Authentic Italian pizza with fresh mozzarella, tomatoes, and basil",
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "500g pizza dough",
      "200g fresh mozzarella",
      "400g canned tomatoes",
      "Fresh basil leaves",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 250°C (480°F)",
      "Roll out pizza dough on floured surface",
      "Spread tomato sauce evenly",
      "Add torn mozzarella pieces",
      "Drizzle with olive oil",
      "Bake for 12-15 minutes until golden",
      "Garnish with fresh basil",
    ],
    tags: ["Vegetarian", "Classic", "Italian"],
    cuisine: "Italian",
    rating: 4.8,
    viewCount: 1250,
    shareCount: 89,
    nutrition: {
      calories: 320,
      protein: 15,
      carbs: 45,
      fat: 12,
    },
  },
  {
    title: "Creamy Carbonara",
    description: "Traditional Roman pasta with eggs, cheese, and pancetta",
    prepTime: "10 mins",
    cookTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: ["400g spaghetti", "200g pancetta", "4 large eggs", "100g Pecorino Romano", "Black pepper", "Salt"],
    instructions: [
      "Cook spaghetti until al dente",
      "Fry pancetta until crispy",
      "Whisk eggs with cheese",
      "Combine hot pasta with pancetta",
      "Add egg mixture off heat",
      "Toss quickly to create creamy sauce",
      "Season with black pepper",
    ],
    tags: ["Traditional", "Comfort Food", "Quick"],
    cuisine: "Italian",
    rating: 4.9,
    viewCount: 2100,
    shareCount: 156,
    nutrition: {
      calories: 580,
      protein: 28,
      carbs: 65,
      fat: 22,
    },
  },
  {
    title: "Vegetarian Lasagna",
    description: "Layered pasta with ricotta, spinach, and marinara sauce",
    prepTime: "30 mins",
    cookTime: "45 mins",
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      "12 lasagna sheets",
      "500g ricotta cheese",
      "300g spinach",
      "400g marinara sauce",
      "200g mozzarella",
      "50g Parmesan",
      "2 eggs",
      "Italian herbs",
    ],
    instructions: [
      "Cook lasagna sheets until al dente",
      "Mix ricotta with eggs and herbs",
      "Sauté spinach until wilted",
      "Layer pasta, ricotta, spinach, sauce",
      "Repeat layers, top with cheese",
      "Bake at 180°C for 45 minutes",
      "Rest for 10 minutes before serving",
    ],
    tags: ["Vegetarian", "Comfort Food", "Family-Friendly"],
    cuisine: "Italian",
    rating: 4.7,
    viewCount: 1800,
    shareCount: 134,
    nutrition: {
      calories: 420,
      protein: 22,
      carbs: 38,
      fat: 18,
    },
  },

  // Chinese Recipes
  {
    title: "Kung Pao Chicken",
    description: "Spicy Sichuan dish with chicken, peanuts, and chili peppers",
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "500g chicken breast, diced",
      "100g roasted peanuts",
      "6 dried chili peppers",
      "3 cloves garlic",
      "2 tbsp soy sauce",
      "1 tbsp rice wine",
      "1 tsp cornstarch",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Marinate chicken with soy sauce and cornstarch",
      "Heat oil in wok over high heat",
      "Stir-fry chicken until golden",
      "Add garlic and chili peppers",
      "Add peanuts and sauce",
      "Stir-fry for 2-3 minutes",
      "Serve with steamed rice",
    ],
    tags: ["Spicy", "Quick", "Protein-Rich"],
    cuisine: "Chinese",
    rating: 4.6,
    viewCount: 1650,
    shareCount: 98,
    nutrition: {
      calories: 380,
      protein: 32,
      carbs: 12,
      fat: 24,
    },
  },
  {
    title: "Vegetable Fried Rice",
    description: "Classic Chinese fried rice with mixed vegetables and eggs",
    prepTime: "15 mins",
    cookTime: "10 mins",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "3 cups cooked rice",
      "2 eggs, beaten",
      "1 cup mixed vegetables",
      "3 green onions",
      "3 tbsp soy sauce",
      "2 tbsp vegetable oil",
      "1 tsp sesame oil",
      "Salt and pepper",
    ],
    instructions: [
      "Heat oil in large wok or pan",
      "Scramble eggs and set aside",
      "Stir-fry vegetables until tender",
      "Add rice and break up clumps",
      "Add soy sauce and sesame oil",
      "Return eggs to pan",
      "Garnish with green onions",
    ],
    tags: ["Vegetarian", "Quick", "Leftover-Friendly"],
    cuisine: "Chinese",
    rating: 4.4,
    viewCount: 2200,
    shareCount: 167,
    nutrition: {
      calories: 280,
      protein: 8,
      carbs: 45,
      fat: 8,
    },
  },
  {
    title: "Sweet and Sour Pork",
    description: "Crispy pork with colorful vegetables in tangy sauce",
    prepTime: "25 mins",
    cookTime: "20 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "500g pork shoulder, cubed",
      "1 bell pepper",
      "1 onion",
      "200g pineapple chunks",
      "3 tbsp ketchup",
      "2 tbsp rice vinegar",
      "2 tbsp sugar",
      "Cornstarch for coating",
    ],
    instructions: [
      "Coat pork in cornstarch",
      "Deep fry until golden and crispy",
      "Stir-fry vegetables until tender",
      "Mix sauce ingredients",
      "Combine pork, vegetables, and sauce",
      "Add pineapple chunks",
      "Serve immediately with rice",
    ],
    tags: ["Sweet", "Crispy", "Colorful"],
    cuisine: "Chinese",
    rating: 4.5,
    viewCount: 1900,
    shareCount: 142,
    nutrition: {
      calories: 450,
      protein: 28,
      carbs: 35,
      fat: 22,
    },
  },

  // Mexican Recipes
  {
    title: "Chicken Tacos al Pastor",
    description: "Marinated chicken with pineapple in soft tortillas",
    prepTime: "30 mins",
    cookTime: "20 mins",
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1kg chicken thighs",
      "12 corn tortillas",
      "1 pineapple, diced",
      "1 onion, diced",
      "Cilantro",
      "Lime wedges",
      "Achiote paste",
      "Chipotle peppers",
    ],
    instructions: [
      "Marinate chicken in achiote and spices",
      "Grill chicken until charred",
      "Warm tortillas on griddle",
      "Slice chicken thinly",
      "Fill tortillas with chicken",
      "Top with pineapple and onion",
      "Garnish with cilantro and lime",
    ],
    tags: ["Street Food", "Spicy", "Authentic"],
    cuisine: "Mexican",
    rating: 4.8,
    viewCount: 2800,
    shareCount: 203,
    nutrition: {
      calories: 320,
      protein: 25,
      carbs: 28,
      fat: 12,
    },
  },
  {
    title: "Black Bean Quesadillas",
    description: "Crispy tortillas filled with seasoned black beans and cheese",
    prepTime: "15 mins",
    cookTime: "15 mins",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "8 flour tortillas",
      "400g black beans",
      "200g Mexican cheese blend",
      "1 bell pepper",
      "1 onion",
      "2 tsp cumin",
      "1 tsp paprika",
      "Sour cream and salsa",
    ],
    instructions: [
      "Sauté onion and bell pepper",
      "Add black beans and spices",
      "Mash beans slightly",
      "Spread mixture on tortillas",
      "Add cheese and fold",
      "Cook in pan until crispy",
      "Serve with sour cream and salsa",
    ],
    tags: ["Vegetarian", "Quick", "Comfort Food"],
    cuisine: "Mexican",
    rating: 4.6,
    viewCount: 1750,
    shareCount: 128,
    nutrition: {
      calories: 380,
      protein: 18,
      carbs: 45,
      fat: 15,
    },
  },
  {
    title: "Beef Enchiladas",
    description: "Rolled tortillas with seasoned beef in red sauce",
    prepTime: "25 mins",
    cookTime: "30 mins",
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "12 corn tortillas",
      "500g ground beef",
      "400ml enchilada sauce",
      "200g cheddar cheese",
      "1 onion",
      "2 tsp chili powder",
      "1 tsp cumin",
      "Cilantro for garnish",
    ],
    instructions: [
      "Brown ground beef with onions",
      "Season with chili powder and cumin",
      "Warm tortillas to make pliable",
      "Fill tortillas with beef mixture",
      "Roll and place in baking dish",
      "Cover with sauce and cheese",
      "Bake at 180°C for 25 minutes",
    ],
    tags: ["Comfort Food", "Baked", "Family-Friendly"],
    cuisine: "Mexican",
    rating: 4.7,
    viewCount: 2100,
    shareCount: 156,
    nutrition: {
      calories: 420,
      protein: 26,
      carbs: 32,
      fat: 20,
    },
  },

  // Indian Recipes
  {
    title: "Butter Chicken",
    description: "Creamy tomato-based curry with tender chicken pieces",
    prepTime: "20 mins",
    cookTime: "40 mins",
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1kg chicken breast",
      "400ml coconut cream",
      "400g canned tomatoes",
      "2 tbsp butter",
      "1 onion",
      "4 cloves garlic",
      "2 tsp garam masala",
      "1 tsp turmeric",
    ],
    instructions: [
      "Marinate chicken in yogurt and spices",
      "Sauté onion and garlic",
      "Add tomatoes and spices",
      "Simmer until thick",
      "Add chicken and cook through",
      "Stir in cream and butter",
      "Serve with basmati rice",
    ],
    tags: ["Creamy", "Spicy", "Popular"],
    cuisine: "Indian",
    rating: 4.9,
    viewCount: 3200,
    shareCount: 245,
    nutrition: {
      calories: 380,
      protein: 32,
      carbs: 12,
      fat: 24,
    },
  },
  {
    title: "Vegetable Biryani",
    description: "Fragrant basmati rice with mixed vegetables and aromatic spices",
    prepTime: "30 mins",
    cookTime: "45 mins",
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "2 cups basmati rice",
      "500g mixed vegetables",
      "1 cup yogurt",
      "2 onions, fried",
      "Whole spices",
      "Saffron",
      "Mint leaves",
      "Ghee",
    ],
    instructions: [
      "Soak rice for 30 minutes",
      "Marinate vegetables in yogurt",
      "Cook rice with whole spices",
      "Layer rice and vegetables",
      "Top with fried onions and saffron",
      "Cook on dum for 45 minutes",
      "Serve with raita",
    ],
    tags: ["Vegetarian", "Aromatic", "Festive"],
    cuisine: "Indian",
    rating: 4.8,
    viewCount: 2600,
    shareCount: 189,
    nutrition: {
      calories: 350,
      protein: 12,
      carbs: 65,
      fat: 8,
    },
  },
  {
    title: "Palak Paneer",
    description: "Creamy spinach curry with soft cottage cheese cubes",
    prepTime: "15 mins",
    cookTime: "25 mins",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "500g fresh spinach",
      "250g paneer",
      "2 tomatoes",
      "1 onion",
      "4 cloves garlic",
      "1 inch ginger",
      "2 tbsp cream",
      "Indian spices",
    ],
    instructions: [
      "Blanch spinach and puree",
      "Sauté onion, garlic, ginger",
      "Add tomatoes and spices",
      "Add spinach puree",
      "Simmer for 10 minutes",
      "Add paneer cubes",
      "Finish with cream",
    ],
    tags: ["Vegetarian", "Healthy", "Green"],
    cuisine: "Indian",
    rating: 4.7,
    viewCount: 2100,
    shareCount: 167,
    nutrition: {
      calories: 280,
      protein: 18,
      carbs: 15,
      fat: 18,
    },
  },

  // Japanese Recipes
  {
    title: "Chicken Teriyaki",
    description: "Glazed chicken with sweet and savory teriyaki sauce",
    prepTime: "15 mins",
    cookTime: "20 mins",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "4 chicken thighs",
      "4 tbsp soy sauce",
      "3 tbsp mirin",
      "2 tbsp sugar",
      "1 tbsp sake",
      "1 tsp ginger",
      "2 green onions",
      "Sesame seeds",
    ],
    instructions: [
      "Mix teriyaki sauce ingredients",
      "Season chicken with salt",
      "Pan-fry chicken skin-side down",
      "Flip and cook through",
      "Add teriyaki sauce",
      "Glaze until sticky",
      "Garnish with green onions",
    ],
    tags: ["Sweet", "Glazed", "Popular"],
    cuisine: "Japanese",
    rating: 4.8,
    viewCount: 2400,
    shareCount: 178,
    nutrition: {
      calories: 320,
      protein: 28,
      carbs: 18,
      fat: 16,
    },
  },
  {
    title: "Vegetable Sushi Bowl",
    description: "Deconstructed sushi with fresh vegetables and sushi rice",
    prepTime: "25 mins",
    cookTime: "20 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "2 cups sushi rice",
      "1 cucumber",
      "1 avocado",
      "1 carrot",
      "Nori sheets",
      "Rice vinegar",
      "Soy sauce",
      "Wasabi",
    ],
    instructions: [
      "Cook sushi rice with vinegar",
      "Julienne cucumber and carrot",
      "Slice avocado",
      "Cut nori into strips",
      "Arrange rice in bowls",
      "Top with vegetables",
      "Serve with soy sauce and wasabi",
    ],
    tags: ["Vegetarian", "Healthy", "Fresh"],
    cuisine: "Japanese",
    rating: 4.5,
    viewCount: 1800,
    shareCount: 134,
    nutrition: {
      calories: 280,
      protein: 6,
      carbs: 58,
      fat: 8,
    },
  },
  {
    title: "Miso Ramen",
    description: "Rich and savory noodle soup with miso broth",
    prepTime: "20 mins",
    cookTime: "30 mins",
    servings: 4,
    difficulty: "Hard",
    ingredients: [
      "4 portions ramen noodles",
      "1L chicken broth",
      "4 tbsp miso paste",
      "2 eggs",
      "200g pork belly",
      "2 green onions",
      "Nori sheets",
      "Bamboo shoots",
    ],
    instructions: [
      "Simmer broth with miso paste",
      "Cook ramen noodles",
      "Soft-boil eggs",
      "Char pork belly",
      "Assemble bowls with noodles",
      "Pour hot broth over",
      "Top with egg, pork, and garnishes",
    ],
    tags: ["Comfort Food", "Hearty", "Warming"],
    cuisine: "Japanese",
    rating: 4.9,
    viewCount: 3100,
    shareCount: 234,
    nutrition: {
      calories: 520,
      protein: 28,
      carbs: 45,
      fat: 26,
    },
  },

  // Thai Recipes
  {
    title: "Pad Thai",
    description: "Classic stir-fried noodles with tamarind, fish sauce, and peanuts",
    prepTime: "20 mins",
    cookTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "400g rice noodles",
      "200g shrimp",
      "3 eggs",
      "100g bean sprouts",
      "3 tbsp tamarind paste",
      "2 tbsp fish sauce",
      "2 tbsp palm sugar",
      "Crushed peanuts",
    ],
    instructions: [
      "Soak rice noodles until soft",
      "Heat oil in wok",
      "Stir-fry shrimp until pink",
      "Push to one side, scramble eggs",
      "Add noodles and sauce",
      "Add bean sprouts",
      "Garnish with peanuts and lime",
    ],
    tags: ["Street Food", "Sweet and Sour", "Popular"],
    cuisine: "Thai",
    rating: 4.7,
    viewCount: 2800,
    shareCount: 201,
    nutrition: {
      calories: 420,
      protein: 22,
      carbs: 58,
      fat: 12,
    },
  },
  {
    title: "Green Curry Vegetables",
    description: "Aromatic coconut curry with fresh vegetables and herbs",
    prepTime: "15 mins",
    cookTime: "20 mins",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "400ml coconut milk",
      "3 tbsp green curry paste",
      "500g mixed vegetables",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar",
      "Thai basil",
      "Lime leaves",
      "Thai chilies",
    ],
    instructions: [
      "Heat thick coconut milk",
      "Fry curry paste until fragrant",
      "Add remaining coconut milk",
      "Add hard vegetables first",
      "Season with fish sauce and sugar",
      "Add soft vegetables",
      "Garnish with basil and chilies",
    ],
    tags: ["Vegetarian", "Spicy", "Aromatic"],
    cuisine: "Thai",
    rating: 4.6,
    viewCount: 2200,
    shareCount: 165,
    nutrition: {
      calories: 280,
      protein: 8,
      carbs: 22,
      fat: 18,
    },
  },
  {
    title: "Tom Yum Soup",
    description: "Hot and sour soup with shrimp, mushrooms, and herbs",
    prepTime: "15 mins",
    cookTime: "15 mins",
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1L chicken broth",
      "300g shrimp",
      "200g mushrooms",
      "3 lemongrass stalks",
      "4 lime leaves",
      "3 Thai chilies",
      "3 tbsp lime juice",
      "2 tbsp fish sauce",
    ],
    instructions: [
      "Bring broth to boil",
      "Add lemongrass and lime leaves",
      "Add mushrooms and chilies",
      "Add shrimp and cook until pink",
      "Season with fish sauce",
      "Add lime juice off heat",
      "Garnish with cilantro",
    ],
    tags: ["Soup", "Spicy", "Light"],
    cuisine: "Thai",
    rating: 4.8,
    viewCount: 2500,
    shareCount: 187,
    nutrition: {
      calories: 180,
      protein: 20,
      carbs: 8,
      fat: 6,
    },
  },
]

export async function seedRecipes() {
  console.log("Starting to seed recipes...")

  try {
    // Create a dummy user for the recipes
    const dummyUser = await prisma.user.upsert({
      where: { email: "admin@cooksmartai.com" },
      update: {},
      create: {
        clerkId: "admin_user",
        firstName: "CookSmart",
        lastName: "Admin",
        email: "admin@cooksmartai.com",
        imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
      },
    })

    console.log("Created/found admin user:", dummyUser.id)

    // Insert all sample recipes
    for (const recipe of sampleRecipes) {
      const createdRecipe = await prisma.globalRecipe.create({
        data: {
          ...recipe,
          userId: dummyUser.id,
        },
      })
      console.log(`Created recipe: ${createdRecipe.title}`)
    }

    console.log(`Successfully seeded ${sampleRecipes.length} recipes!`)
  } catch (error) {
    console.error("Error seeding recipes:", error)
  } finally {
    await prisma.$disconnect()
  }
}

seedRecipes()
